config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/sign_out_user', to: 'users#sign_out_user', as: 'sign_out_user'
  # get '/users/sign_out', to: 'devise/sessions#destroy'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "groups#index"
  get '/splash', to: 'splash#index'
  resources :expenses, only: [:new, :create]
  resources :groups, only: [:index, :show, :new, :create]

  # get '*path', to: redirect('/'), via: :all, constraints: lambda { |req| !req.path.starts_with?('/rails/active_storage') }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :group_expenses
  has_many :groups, through: :group_expenses

  validates :name, presence: true
  validates :amount, presence: true
  validates :amount, numericality: { greater_than_or_equal_to: 0 }

  accepts_nested_attributes_for :group_expenses
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user, class_name: 'User'
  has_many :group_expenses
  has_many :expenses, through: :group_expenses
  has_one_attached :icon

  validates :name, presence: true
end

app/models/group_expense.rb
class GroupExpense < ApplicationRecord
  belongs_to :group
  belongs_to :expense
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :expenses
  has_many :groups

  validates :name, presence: true
  validates :role, presence: true
  validates :name, length: { maximum: 100 }
  validates :role, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!, unless: :devise_controller?
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def after_sign_out_path_for(_resource_or_scope)
    splash_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name role email password])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name role email password current_password])
  end

  def authenticate_user!
    return if devise_controller? || (params[:controller] == 'splash' && params[:action] == 'index')

    redirect_to splash_path unless user_signed_in?
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :authenticate_user!
  layout 'application'

  def new
    @groups = Group.all
    @expense = Expense.new
  end

  def create
    @expense = Expense.new(expense_params)
    @expense.author = current_user

    if @expense.save
      group_id = params[:expense][:group_ids]
      if group_id.present?
        group = Group.find(group_id)
        GroupExpense.create(expense: @expense, group:)
      end

      redirect_to group_path(group), notice: 'Expense created successfully.'
    else
      flash.now[:error] = 'Failed to create expense.'
      @groups = Group.all
      render :new, status: :unprocessable_entity
    end
  end

  private

  def expense_params
    params.require(:expense).permit(:name, :amount, group_ids: [])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  layout 'application'
  def index
    @groups = if params[:order] == 'ancient'
                current_user.groups.includes(:expenses, :group_expenses).order(created_at: :asc)
              else
                current_user.groups.includes(:expenses, :group_expenses).order(created_at: :desc)
              end

    @group_expenses = 0
    @groups.each do |group|
      @group_expenses += group.expenses.sum(:amount)
    end
  end

  def show
    @group = current_user.groups.includes(:expenses, :group_expenses).find(params[:id])
    @expenses_asc = @group.expenses.order(created_at: :asc)
    @total_expense = @group.expenses.sum(:amount)
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.user = current_user
    if @group.save
      redirect_to groups_path, notice: 'Group created successfully.'
    else
      # puts @group.errors.full_messages
      flash.now[:error] = 'Error creating the group.'
      render :new, status: :unprocessable_entity
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
    render 'splash'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def sign_out_user
    sign_out(current_user)
    redirect_to root_path, notice: 'Signed out successfully'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/views/expenses/new.html.erb
<header class="header">
    <div class="top">
        <!-- <img src="#" alt="Burger menu"> -->
        <%= link_to groups_path, class: "btn btn-primary" do %>
            <i class="fa fa-arrow-left" aria-hidden="true"></i>
        <% end %>
        <h1>NEW EXPENSE</h1>
        <%= link_to 'SIGN OUT', '/sign_out_user', class: "btn-user" %>
    </div>
</header>
<div class="form-wrapper">
  <div class="notification">
      <%= flash[:notice] %>
      <%= flash[:error] %>
      <%= flash[:alert] %>
  </div>
  <div class="create-cat">
    <%= form_with(model: @expense, url: expenses_path, method: :post, local: true) do |f| %>
      <div class="field">
        <%= f.label :name, class: "label" %>
        <%= f.text_field :name %>
      </div>
      <div class="field">
        <%= f.label :amount, class: "label" %>
        <%= f.number_field :amount %>
      </div>
      <div class="field">
        <%= f.label :group_ids, class: "label" %>
        <%= f.collection_select :group_ids, current_user.groups, :id, :name, { prompt: 'Select a group' }, { multiple: false, class: 'select' } %>
      </div>
      <%= f.submit "ADD EXPENSE", class: "button" %>
    <% end %>
  </div>
</div>

app/views/groups/index.html.erb
<header class="header">
    <div class="top">
        <!-- <img src="#" alt="Burger menu"> -->
        <a href=""><i class="fa-solid fa-bars"></i></a>
        <h1>CATEGORIES</h1>
        <%= link_to '/sign_out_user', class: "btn-user" do %>
            <i class="fa-solid fa-lock"></i>
          <% end %>
        <!-- <i class="fa fa-search" aria-hidden="true"></i> -->
    </div>
    <div class="bottom">
        <div>
            <%= link_to "Most recent", root_path(order: :recent), class: "recent" %>
            <i class="fa-solid fa-circle toggleable"></i>
        </div>        
        <div>
            <%= link_to "Most ancient", root_path(order: :ancient), class: "ancient" %>
            <i class="fa-solid fa-circle toggleable"></i>
        </div>
    </div>
</header>
<div class="notification">
    <%= flash[:notice] %>
    <%= flash[:error] %>
    <%= flash[:alert] %>
</div>
<div class="list-groups">
    <div class="total-wrapper">
        <p class="total">Total amount</p>
        <p class="price">$<%= @group_expenses %></p>
    </div>
    <ul class="groups">
        <% @groups.each do |group| %>
            <li>
            <%= link_to group_path(group) do %>
                <div class="icon-name-wrapper">
                <%= image_tag(group.icon, class: "icon", alt: "Icon") %>
                <div>
                    <p class="total"><%= group.name %></p>
                    <p class="gn-date"><%= group.created_at %></p>
                </div>
                </div>
                <p class="tr-price">$<%= group.expenses.sum(:amount) %></p>
            <% end %>
            </li>
        <% end %>
    </ul>
    <div class="add-category-wrapper">
        <a href="/groups/new" class="add-category">+</a>
    </div>  
</div>

app/views/groups/new.html.erb
<header class="header">
    <div class="top">
        <!-- <img src="#" alt="Burger menu"> -->
        <%= link_to groups_path, class: "btn btn-primary" do %>
            <i class="fa fa-arrow-left" aria-hidden="true"></i>
        <% end %>
        <h1>NEW CATEGORY</h1>
        <%= link_to 'SIGN OUT', '/sign_out_user', class: "btn-user" %>
    </div>
</header>
<div class="notification">
    <%= flash[:notice] %>
    <%= flash[:error] %>
    <%= flash[:alert] %>
</div>
<div class="create-cat">
  <%= form_with(model: @group, url: groups_path, method: :post, local: true, multipart: true ) do |form| %>
    <div class="field">
      <%= form.label :name, "Name" %>
      <%= form.text_field :name, id: "name", placeholder: "Name" %>
    </div>
    <div class="field">
      <%= form.label :icon, "Icon" %>
      <%= form.file_field :icon, id: "icon" %>
    </div>
    <%= form.submit "ADD CATEGORY", class: "button" %>
  <% end %>
</div>

app/views/groups/show.html.erb
<header class="header">
    <div class="top">
        <!-- <img src="#" alt="Burger menu"> -->
        <%= link_to groups_path, class: "btn btn-primary" do %>
            <i class="fa fa-arrow-left" aria-hidden="true"></i>
        <% end %>
        <h1>EXPENSES</h1>
        <%= link_to 'SIGN OUT', "/sign_out_user", method: :delete, class: "btn-user" %>
    </div>
</header>
<div class="notification">
    <%= flash[:notice] %>
    <%= flash[:error] %>
    <%= flash[:alert] %>
</div>
<div class="list-groups">
    <div class="details">
        <%= image_tag(@group.icon, class: "icon", alt: "Icon") %>
        <p class="total"><%= @group.name %></p>
    </div>
    <div class="line-wrapper">
        <hr class="line">
    </div>
    <div class="one-transaction">
        <div class="transaction-data">
            <h2>DETAILS</h2>
            <p class="gn-date"><%= @group.created_at %><p/>
        </div>
        <div class="item">
            <hr class="line-short">
            <% @expenses_asc.each do |expense|%>
                <div class="p-wrapper">
                    <p><%= expense.name %></p>
                    <p>$<%= expense.amount %></p>
                </div>
            <% end %>
        </div>
        <div class="total-transaction">
            <h2>TOTAL EXPENSE</h2>
            <p class="price">$<%= @total_expense %></p>
        </div>
    </div>

    <div class="add-category-wrapper">
        <a href="/expenses/new" class="add-category">+</a>
    </div> 
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SmartBudgetRorCapstone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <%= stylesheet_link_tag "groups", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "details", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "category", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/splash/splash.html.erb
<div class="splash">
    <div class="title">
        <%= image_tag("logo.png", class: "logo", alt: "LOGO") %>
        <h1>Smart Budget</h1>
    </div>
    <div class="links">
        <a href="/users/sign_in" class="sign_in">LOG IN</a>
        <a href="users/sign_up" class="sign_up">SIGN UP</a>
    </div>
</div>